/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "LCD.h"
#include "EXTI.h"

void Clock_Init() {
	RCC_GPIOA_CLOCK_ENABLE();
	RCC_GPIOB_CLOCK_ENABLE();
	RCC_AFIO_CLOCK_ENABLE();

}
void EXTI9PB9_ISR(void) {
	LCD_voidWriteStrig("EXTI9 is Happend");
	LCD_voidGoTo(3, 2);
	LCD_voidWriteStrig(" ___|---");
	_delay_ms(500);
	LCD_ClrLCD();

}
void EXTI8PB8_ISR(void) {
	LCD_voidWriteStrig("EXTI8 is Happend");
	LCD_voidGoTo(3, 2);
	LCD_voidWriteStrig(" ___|---");
	_delay_ms(500);
	LCD_ClrLCD();

}
int main(void) {

	Clock_Init();
	LCD_voidLCDInit();


	EXTI_CONFIG EXTIconfig;
	EXTIconfig.EXTI_PORT_PIN = EXTI9PB9;
	EXTIconfig.IRQ_EN = EXTI_IRQ_Enable;
	EXTIconfig.P_IRQ_CallBack = EXTI9PB9_ISR;
	EXTIconfig.TRIGGER = EXTI_Falling_Edge;
	MCAL_EXTI_GPIO_Init(&EXTIconfig);

	EXTIconfig.EXTI_PORT_PIN = EXTI8PB8;
	EXTIconfig.IRQ_EN = EXTI_IRQ_Enable;
	EXTIconfig.P_IRQ_CallBack = EXTI8PB8_ISR;
	EXTIconfig.TRIGGER = EXTI_Rising_Edge;
	MCAL_EXTI_GPIO_Init(&EXTIconfig);
	while (1) {
	}
}
