/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "LCD.h"
#include "KPD.h"

void Clock_Init() {
	RCC_GPIOA_CLOCK_ENABLE();
	RCC_GPIOB_CLOCK_ENABLE();

}
int main(void) {
	Clock_Init();
	LCD_voidLCDInit();
	Keypad_init();
	//LCD_voidWriteChar('A');
	while (1) {
		uint8_t key = Keypad_getkey();
		//display the key on the LCD
		if (key != 0xff) {
			LCD_voidWriteChar(key);
		}
	}
}
