/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


typedef volatile unsigned int vuint32_t ;
 #include <stdint.h>
 #include <stdlib.h>
 #include <stdio.h>
//GPIO_A
#define GPIOA_BASE     0x40010800
#define GPIOA_CRH     *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_CRL     *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_ODR     *(volatile uint32_t *)(GPIOA_BASE + 0x0C)

//RCC
#define RCC_BASE       0x40021000
#define RCC_APB2ENR   *(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR      *(volatile uint32_t *)(RCC_BASE + 0x04)
#define RCC_CR        *(volatile uint32_t *)(RCC_BASE + 0x00)
//EXTI
#define EXTI_BASE      0x40010400
#define EXTI_IMR      *(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR     *(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR       *(volatile uint32_t *)(EXTI_BASE + 0x14)

//AFIO
#define AFIO_BASE       0x40010000
#define AFIO_EXTICR1   *(volatile uint32_t *)(AFIO_BASE + 0x08)

//AFIO
#define NVIC_BASE       0xE000E100
#define NVIC_EXTIE0   *(volatile uint32_t *)(NVIC_BASE + 0x00)

void Clock_Init(){
	RCC_APB2ENR |=(1<<2); //I/O port A clock enable
	RCC_APB2ENR |=(1<<0); // Alternate function I/O clock enable
}
void GPIO_A_INIT(){
	// PIN 13 OUTPUT
	 GPIOA_CRH   &= 0xFF0FFFFF;
	 GPIOA_CRH   |= 0x00200000;
	 // pin 0 input
	 GPIOA_CRL |= (0b01<<2); // Floating input (reset state)
}

int main(void)
 {
	Clock_Init();
	GPIO_A_INIT();

	AFIO_EXTICR1 |= (0b0000<<0);
	EXTI_IMR |=1<<0; // enable line 0 EXTI
	EXTI_RTSR |=1<<0; // enable rising line 0 EXTI

	NVIC_EXTIE0 |=1<<6; // enable NVIC IRQ6 from ARM corex m3


	while(1);
 }
void EXTI0_IRQHandler()
{
	//toggle pin 13 port A
	GPIOA_ODR ^=  1<<13 ;
	EXTI_PR |=1<<0; // clear pending flag
}
